import { defineConfig, loadEnv } from 'vite'
import type { ViteDevServer } from 'vite'
import type { IncomingMessage, ServerResponse } from 'node:http'
import path from 'path'
import fs from 'fs'

const excludedDirs = ['node_modules/**', 'dist/**', 'deploy_tools/**']
const isWatchBuild = process.argv.includes('--watch')

// 从 .env 读取构建期密钥（不带前缀过滤，确保能读到 MAISI_API_KEY）。
// CDN/IIFE 构建注入真实 key；若 .env 缺失则注入空串（与 npm 构建一致）。
const env = loadEnv(process.env.NODE_ENV || 'production', __dirname, '')
const MAISI_API_KEY = env.MAISI_API_KEY || ''

export default defineConfig({
  build: {
    lib: {
      entry: path.resolve(__dirname, 'index.ts'),
      name: 'keepworkSDK',
      fileName: (format: string) => `keepworkSDK.${format}.js`,
      formats: ['iife']
    },
    // Output right beside the source file
    outDir: 'dist',
    sourcemap: true, // Enable for debugging
    minify: 'terser', // Use terser for minification
    emptyOutDir: true,
    rollupOptions: {
      // No external dependencies to bundle everything
      external: [],
      output: {
        exports: 'named', // Fix the named/default export warning
        globals: {
          'keepworkSDK': 'keepworkSDK'
        }
      }
    },
    ...(isWatchBuild ? {
      // Only enable watch mode for CLI invocations that explicitly pass --watch.
      watch: {
        include: ['src/**', 'index.ts', 'indexCore.ts', 'indexAIChat.ts'],
        exclude: excludedDirs
      }
    } : {})
  },
  plugins: [
    {
      name: 'copy-static-assets',
      writeBundle() {
        // Copy standalone HTML files that are deployed alongside the IIFE bundle
        const staticFiles = ['src/digital-human/DigitalHumanFrame.html']
        for (const file of staticFiles) {
          const src = path.resolve(__dirname, file)
          const dest = path.resolve(__dirname, 'dist', path.basename(file))
          if (fs.existsSync(src)) {
            fs.copyFileSync(src, dest)
            console.log(`Copied ${file} → dist/${path.basename(file)}`)
          }
        }
      }
    },
    {
      name: 'serve-static',
      configureServer(server: ViteDevServer) {
        // Serve files from the keepworkSDK directory for the dev server
        server.middlewares.use((req: IncomingMessage, res: ServerResponse, next: () => void) => {
          // Redirect root to test page
          if (req.url === '/') {
            res.writeHead(302, { Location: '/test/testKeepworkSDK.html' })
            res.end()
            return
          }
          // 测试密钥注入端点：从本地 .env 读取真密钥，生成 window.__TEST_SECRETS__。
          // 仅 dev server 内存生成，永不写盘、不进构建产物/Git。test/*.html 通过
          // <script src="./env.js"> 加载它；.env 缺失时各字段为空串，页面回落占位符。
          const urlPath = (req.url || '').split('?')[0]
          if (urlPath === '/test/env.js') {
            const testSecrets = {
              VOLC_ACCESS_TOKEN: env.VOLC_ACCESS_TOKEN || '',
            }
            const body = `// Auto-generated by Vite dev server from local .env — NOT committed, NOT bundled.\n`
              + `window.__TEST_SECRETS__ = ${JSON.stringify(testSecrets)};\n`
            res.writeHead(200, {
              'Content-Type': 'application/javascript; charset=utf-8',
              'Cache-Control': 'no-store',
            })
            res.end(body)
            return
          }
          next()
        })
      }
    }
  ],
  // Development server for testing
  server: {
    port: 5001, // Different port from your Nuxt app
    open: '/test/testKeepworkSDK.html',
    cors: true,
    host: '0.0.0.0', // Allow external connections
    watch: {
      ignored: excludedDirs
    },
    // 将 /core/v0 API 请求转发到 keepwork 正式服务。
    // 数字人 iframe 默认从本 dev server (5001) 加载，其内部 SDK 使用相对路径
    // baseURL '/core/v0' 发起 RTC token 等请求；这些相对路径会基于 iframe 自身
    // 的 origin(5001) 解析，因此必须在本 server 也配置同样的 proxy，否则会 404。
    proxy: {
      '/core/v0': {
        target: 'https://api.keepwork.com',
        changeOrigin: true,
        configure: (proxy) => {
          proxy.on('proxyReq', (proxyReq) => {
            proxyReq.setHeader('Origin', 'https://keepwork.com')
            proxyReq.setHeader('Referer', 'https://keepwork.com/')
          })
        }
      }
    }
  },
  // No publicDir needed - Vite serves files from project root directly
  publicDir: false,
  define: {
    'process.env.NODE_ENV': '"development"',
    // 构建期注入 maisi API key（CDN 自用产物含真实 key）
    __MAISI_API_KEY__: JSON.stringify(MAISI_API_KEY),
  },
  // Resolve settings
  resolve: {
    alias: {
      '@': path.resolve(__dirname, '../../../'),
    }
  }
})
